### ISSUE TITLE
Distill design doc into focused gameplay concept.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CAyZ#1]
The design doc has some good stuff in it, but it's essentially a stream of consciousness from the both of us.  From the sheet, derive a good gameplay concept including:

Long-term play (campaign scope).
Short-term play (session scope).

Both in terms that can be actioned via code and editor.

This should result in a page in the GitHub wiki.

**Comment by dgibso29** [comment]
Made init [design page](https://github.com/Bubbus/CAyZ/wiki/Design) in wiki

**Comment by Bubbus** [comment]
Work done on design page.  Please check it over and add/edit/remove as needed.  Keep it specific/make it specific as we'll need to refer to this during dev for answers.

**Comment by dgibso29** [comment]
Looked over all of this and am happy. Nothing jumped out to add -- you've covered everything quite nicely.
