### ISSUE TITLE
[Set Piece] Campbeltown Substation

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/CAyZ#10]
- [ ] Creation
- [ ] Review
- [ ] Lights off scripting (@Bubbus )
- [ ] Final review & systems testing

![20200812092607_1](https://user-images.githubusercontent.com/22088666/90021487-56984b00-dc7f-11ea-9674-bf91d449dc42.jpg)

Could be a potential objective -- Knock out or restore power? Otherwise a viable location for supplies, and potential faction outpost.

**Comment by Bubbus** [comment]
I wrote a script a while back to kill all lights in an area, remind me and I can tie it into this.  Make a task if needed or make it a part of this task.

**Comment by dgibso29** [comment]
Location is close to starting camp. Good location for some basic supplies -- tools, radios, etc.
