### ISSUE TITLE
[Set Piece] Campbeltown Port - RN Base?

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/CAyZ#11]
![20200812092619_1](https://user-images.githubusercontent.com/22088666/90021567-72035600-dc7f-11ea-930b-35a5e69f4bf6.jpg)

Only major port on the map. Good possible location for a current or former Royal Navy/Marine base.

**Comment by Bubbus** [comment]
Could be a good place to find an escape boat.  Perhaps on a trailer in the warehouse.  All docked boats sunk by waterborne anomalies, escape boat needs restoration.

I'm having ideas about Campbeltown being a dense zombie area with holdout faction areas.  Depends on the zombie origin story how this comes around.
