### ISSUE TITLE
[Set Piece] Glenramskill Military Installation

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/CAyZ#15]
![20200812093137_1](https://user-images.githubusercontent.com/22088666/90022045-04a3f500-dc80-11ea-8b3f-0e6de73c2ada.jpg)

This screams high security military facility.

**Comment by Bubbus** [comment]
Yes, love the radar - could give it some meteorological purpose for one of the escape objectives.  Find other radar dishes to provide alternative objective locations.

Also contains a large port like in Campbeltown, need some situation explaining no boats.
