### ISSUE TITLE
Identify camp-site location

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CAyZ#2]
We're agreed that the mission starts at a campsite.  Find a good place for it and set down the initial setpiece.

An ideal location is a plausible place for a campsite, provides the players with plenty to do within a near distance with new objectives available with transport or otherwise.  Bonus points if the players may plausibly build up the site or a nearby location.

**Comment by dgibso29** [comment]
There's a great spot to the south of the eastern port town on a hill -- will get a screenshot up of it.

**Comment by dgibso29** [comment]
Possible camp site locaiton.
![20200811192453_1](https://user-images.githubusercontent.com/22088666/89959580-c3253280-dc0a-11ea-8264-9f374e69147b.jpg)
![20200811192539_1](https://user-images.githubusercontent.com/22088666/89959581-c3bdc900-dc0a-11ea-9d4c-f5b8ec1efab8.jpg)

Thoughts @Bubbus ?

**Comment by Bubbus** [comment]
Looks good, go get it!

**Comment by dgibso29** [comment]
Narrowed down, slightly to the west (200m or so) and much nicer:
![20200812092016_1](https://user-images.githubusercontent.com/22088666/90021254-03be9380-dc7f-11ea-9f65-8495862fced4.jpg)
![20200812092009_1](https://user-images.githubusercontent.com/22088666/90021257-04572a00-dc7f-11ea-8cc2-894f52e2c042.jpg)

**Comment by Bubbus** [comment]
Looks like we're settled on this place, I like it.  Closing.
