### ISSUE TITLE
Item availability.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CAyZ#3]
Not everything will be available in Kintyre.  We should figure out what kinds of items exist in the map.  Mostly British gear since we're in Scotland but anything we can tie a plausible story to is fair game.

Might get some hints from the design doc.  We should turn this into a page on the wiki.  Doesn't need to be an exhaustive list: categories broad and narrow are fine: "UK small arms", "old civilian vehicles".

Specifics like "an AK and M27 from weapon familiarity exercises" are fair game but should probably form part of a setpiece description as they are exceptions and case-by-case.

**Comment by Bubbus** [comment]
Did some work: https://github.com/Bubbus/CAyZ/wiki/Items

Check it out when you've got time.  Close this up when you're happy.

**Comment by dgibso29** [comment]
Couple of notes:
Weapons: If castle = gun smugglers, we have the opportunity to have non-UK guns if desired. Same thing if we do the super rich guy -- his guards (see: PMC) might have anything. These would be pretty location-dependent but worth mentioning. I've made the edit.

Everything looks good @Bubbus ! You're clear for #17
