### ISSUE TITLE
Faction design.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CAyZ#4]
Who's out there?  Let's look at the map and decide who could live in certain places.  This will depend on how long The Incident™ has been going on for, how much territory they have, what's in their territory, what they have available, who they are.

The military are going to be a clear contender, there should be some explanation for why the entire place isn't under martial law.  Too early to be applicable, something happening to them, both?

Let's write pages for them in a way that makes them easily actionable.  Specifics about territory, gear, hostility/not, vague political lines if applicable.

**Comment by dgibso29** [comment]
Created [wiki page ](https://github.com/Bubbus/CAyZ/wiki/Factions)

**Comment by Bubbus** [comment]
Added a few, edit to taste m8.

**Comment by dgibso29** [comment]
Took a look. Excellent work. Minor addition of a possible additional faction.

**Comment by Bubbus** [comment]
Good start for the initial AO then.  Closing for now, as we open up the playable space we'll have scope to add new factions in.
