### ISSUE TITLE
[Set Piece] Campbeltown Elementary School

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/CAyZ#9]
![20200812092403_1](https://user-images.githubusercontent.com/22088666/90021429-408a8a80-dc7f-11ea-9eb8-b18c428edb7e.jpg)

Good candidate for a faction outpost or something along those lines.

**Comment by Bubbus** [comment]
Take care with AI near those platforms - in a previous op zombies liked to walk through the walls and hurt players through the floor.  Probably good idea to line around the base with barbed wire or impassable objects.
